import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Heart, Phone, MapPin, Mail, ShieldCheck, Users, FileText } from 'lucide-react'
import { services, phoneDisplay, phoneHref, whatsapp } from '@/data/site'
import { Testimonials, FAQ } from '@/components/HomeInteractive'
import { SimpleForm } from '@/components/Forms'
import { HeroCarousel } from '@/components/HeroCarousel'
export default function Home(){return <>
 <section className="hero"><HeroCarousel/><div className="hero-content"><p className="kicker">Compassionate care · Nairobi</p><h1 className="display">We walk with you through every step.</h1><p>Compassionate funeral services in Nairobi. Available 24 hours.</p><a className="btn" href={whatsapp}><Heart size={17}/>Speak to Our Team</a></div></section>
 <section className="section family-note"><div className="inner"><p className="kicker">A note to families</p><blockquote>“When someone you love has died, even the smallest decision can feel heavy. You do not have to carry it alone. We are here to listen, to guide, and to take each next step with you.”</blockquote><a href={phoneHref} className="big-phone"><Phone/> {phoneDisplay}</a><p className="muted">24-hour phone & WhatsApp support</p></div></section>
 <section className="section" id="services"><div className="inner"><div className="section-head"><div><p className="kicker">How we can help</p><h2>Care for every farewell</h2></div><p>Every family, faith and life is different. We listen first, then shape practical support around what matters to you.</p></div><div className="service-grid">{services.map(s=><article className="service-card" key={s.slug}><Image src={s.image} alt={`${s.name} — Elijah Farewell Services`} width={600} height={450}/><div className="service-body"><p className="kicker">{s.eyebrow}</p><h3>{s.name}</h3><p>{s.description}</p><Link className="text-link" href={`/services/${s.slug}`}>Enquire About This Service <ArrowRight size={15}/></Link></div></article>)}</div></div></section>
 <section className="split" id="pre-planning"><div className="split-image" style={{backgroundImage:"url('/images/family-rose.jpg')"}}/><div className="split-content"><p className="kicker">Planning ahead</p><h2>A thoughtful gift to those you love</h2><p className="muted">Pre-planning lets your wishes be known and lifts the weight of difficult decisions from your family. The conversation is private, gentle and entirely at your pace.</p><ol className="steps"><li>Choose Your Preferences</li><li>Document Your Wishes</li><li>We Handle the Rest</li></ol><Link className="btn" href="/pre-planning">Learn about pre-planning <ArrowRight size={16}/></Link></div></section>
 <section className="section dark"><div className="inner"><div className="center"><p className="kicker">Words from families</p><h2>Thank you for trusting us</h2></div><Testimonials/></div></section>
 <section className="about-strip" id="about"><div className="photo"/><div className="split-content"><p className="kicker">Our story</p><h2>Serving Nairobi families since 1998</h2><p>Elijah Farewell Services was founded on a simple promise: that every family should be met with patience, dignity and honest guidance.</p><p className="muted">Our trained team works alongside churches, hospitals, counsellors and institutions across Nairobi.</p><div className="values"><div className="value"><Heart/><h3>Compassion</h3><p>We listen without judgement.</p></div><div className="value"><ShieldCheck/><h3>Integrity</h3><p>Clear guidance, always.</p></div><div className="value"><Users/><h3>Community</h3><p>Rooted here in Nairobi.</p></div><div className="value"><FileText/><h3>Professional care</h3><p>Experienced and accountable.</p></div></div><Link href="/about" className="text-link">Meet our team <ArrowRight size={15}/></Link></div></section>
 <section className="section"><div className="inner"><div className="center narrow"><p className="kicker">Practical guidance</p><h2>Questions families often ask</h2><p className="muted">Simple answers for a difficult time. If you would rather speak with someone, our team is here at any hour.</p></div><FAQ/></div></section>
 <section className="section contact-band" id="contact"><div className="inner contact-grid"><div><p className="kicker">We are here</p><h2>Tell us how we can support you</h2><p className="muted">There is no pressure and no need to have all the answers. Begin with what you know.</p><div className="contact-list"><a href={phoneHref}><Phone/> {phoneDisplay}</a><a href="mailto:care@elijahfarewellservices.co.ke"><Mail/> care@elijahfarewellservices.co.ke</a><p><MapPin/> Nairobi, Kenya</p></div></div><SimpleForm/></div></section>
 </>}
