'use client'
import { useState, useEffect, FormEvent } from 'react'

declare global { interface Window { grecaptcha?: { ready:(cb:()=>void)=>void; execute:(key:string,options:{action:string})=>Promise<string> } } }
function CaptchaField({action}:{action:string}){const [token,setToken]=useState('');useEffect(()=>{const key=process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY;if(!key){setToken('development-token');return}let attempts=0;const timer=setInterval(()=>{attempts++;if(window.grecaptcha){clearInterval(timer);window.grecaptcha.ready(()=>window.grecaptcha!.execute(key,{action}).then(setToken))}else if(attempts>30)clearInterval(timer)},200);return()=>clearInterval(timer)},[action]);return <input type="hidden" name="captchaToken" value={token}/>}

type Kind='contact'|'pre-plan'|'newsletter'
export function SimpleForm({kind='contact'}:{kind?:Kind}){
 const [status,setStatus]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('Sending…');const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));try{const r=await fetch(`/api/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);setStatus(j.message||'Thank you. Our team will be in touch.');form.reset()}catch(err){setStatus(err instanceof Error?err.message:'Please call our team for assistance.') }}
 if(kind==='newsletter')return <form className="newsletter" onSubmit={submit}><label htmlFor="resource-email">Receive gentle grief resources</label><div><input id="resource-email" name="email" type="email" placeholder="Your email address" required/><button>Sign up</button></div><CaptchaField action="newsletter"/><p role="status">{status}</p></form>
 return <form className="form" onSubmit={submit}><div className="field-grid"><label>Full name<input name="name" required autoComplete="name"/></label><label>Phone number<input name="phone" type="tel" required autoComplete="tel"/></label><label>Email address<input name="email" type="email" required autoComplete="email"/></label>{kind==='pre-plan'?<label>Preferred consultation date<input name="preferredDate" type="date"/></label>:<label>Nature of enquiry<select name="nature" defaultValue=""><option value="" disabled>Please select</option><option>Immediate assistance</option><option>Funeral arrangements</option><option>Pre-planning</option><option>Grief support</option><option>Other</option></select></label>}</div>{kind==='contact'&&<label>Your message<textarea name="message" rows={5} required/></label>}<CaptchaField action={kind}/><button className="btn" type="submit">{kind==='pre-plan'?'Request a consultation':'Send enquiry'}</button><p className="form-status" role="status">{status}</p><small>This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.</small></form>
}

export function MemorialForm(){const [status,setStatus]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('Creating your tribute…');const data=new FormData(e.currentTarget);const r=await fetch('/api/memorial',{method:'POST',body:data});const j=await r.json();if(r.ok)location.href=`/memorials/${j.id}`;else setStatus(j.error||'We could not create the memorial.')}return <form className="form" onSubmit={submit}><label>Full name of deceased<input name="name" required/></label><div className="field-grid"><label>Date of birth<input type="date" name="birthDate" required/></label><label>Date of passing<input type="date" name="passingDate" required/></label></div><label>Photograph<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required/></label><label>Tribute message<textarea name="tribute" rows={8} required maxLength={3000}/></label><CaptchaField action="memorial"/><button className="btn">Create memorial tribute</button><p role="status">{status}</p><small>Tributes are reviewed with care. Please upload only a photograph you have permission to share.</small></form>}
